services:
  - type: web
    name: mortalidad-colombia-2019
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2